### ISSUE TITLE
Error in viz_state with default col_names argument

### ISSUE THREAD

**Issue by curlette** [probcomp/cgpm#161]
Index out of bounds error. 
<img width="1090" alt="screen shot 2016-11-01 at 9 46 12 pm" src="https://cloud.githubusercontent.com/assets/6578088/19918600/0323d172-a0a3-11e6-93be-50ff6d185e60.png">

**Comment by leocasarsa** [comment]
Is this notebook in some probcomp? If not, can I get a copy of the bdb (maybe upload it to probcomp-4:/scratch/home/casarsa/jupyter)? It would be very helpful to have a working copy.
