### ISSUE TITLE
Improve ordering of columns, views, and rows in viz_state 

### ISSUE THREAD

**Issue by curlette** [probcomp/cgpm#164]
To create more compelling state visualizations:

- within each view, order the columns such that the leftmost columns have the highest marginal likelihood (and the rightmost the least).

- within each view, the topmost clusters should have the highest marginal likelihood.

- within each cluster, the topmost rows should have the highest marginal likelihood.

**Comment by fsaad** [comment]
The ordering is implemented in the version of `render.py` on master:

https://github.com/probcomp/cgpm/blob/7d3d1ca60f1595ff81bb9a4f57f12be11f049d85/src/utils/render.py#L148-L193
