### ISSUE TITLE
Why is the category assignment treated as an output variable in the View CGPM?

### ISSUE THREAD

**Issue by leocasarsa** [probcomp/cgpm#171]
https://github.com/probcomp/cgpm/blob/master/src/mixtures/view.py#L46-L49

I currently find it useful to treat the category assignment as a different type of variable (`latents`) than the observable output variables. Is there a conceptual reason why the category assignment must be exposed as an output in View?

**Comment by leocasarsa** [comment]
It is also confusing that the category assignment variables are not stored under the `X` attribute.

**Comment by fsaad** [comment]
The CRP cgpm which generates the category assignment allows for reusable compositional implementations of `simulate` and `logpdf`.
https://github.com/probcomp/cgpm/blob/master/src/mixtures/view.py#L298-L302

The `dim` object takes the category assignment as a required input variable, allowing us to build a composite cgpm network comprised of the CRP cgpm and the individual `dim` objects in the view:

Treating the category assignment as an exposed latent variable allows us to

1. query/constrain it in `View.simulate` and `View.logpdf`:
https://github.com/probcomp/cgpm/blob/master/src/mixtures/view.py#L250
https://github.com/probcomp/cgpm/blob/master/src/mixtures/view.py#L269

2. use `View.incorporate`: https://github.com/probcomp/cgpm/blob/master/src/mixtures/view.py#L149
for both

(i) an external user wishing to specify a cluster assignment for the new row, such as `state.py`
https://github.com/probcomp/cgpm/blob/master/src/crosscat/state.py#L222

(ii) by the internal gibbs transition operator
https://github.com/probcomp/cgpm/blob/master/src/mixtures/view.py#L322

It is also possible to add an MML extension (using the existing `AND EXPOSE` keyword) to provide the cluster assignment in each view to BayesDB. However, the non-parametric nature of the number of cluster assignments makes it a little tricky.

**Comment by leocasarsa** [comment]
I understand and that is indeed a very useful functionality. 

What left me confused was the fact that the attribute `X` does differentiate between the observables and the exposed latent (`X` only stores the observables) , while the `outputs` attribute does not.

**Comment by leocasarsa** [comment]
Suggestion: add the exposed latent to the data table `X`
