### ISSUE TITLE
[View CGPM] Incorporate and Unincorporate do not update data table representation

### ISSUE THREAD

**Issue by leocasarsa** [probcomp/cgpm#173]
Is that the expected behavior?

https://github.com/probcomp/cgpm/blob/master/src/mixtures/view.py#L143-L175

```
import numpy as np

from cgpm.mixtures.view import View

def initialize_view():
    data = np.array([[1, 1]])
    D = len(data[0])
    outputs = range(D)
    X = {c: data[:, i].tolist() for i, c in enumerate(outputs)}
    view = View(
        X,
        outputs=[1000] + outputs,
        alpha=1.,
        cctypes=['bernoulli']*D,
        hypers={
            i: {'alpha': 1., 'beta': 1.} for i in outputs},
        Zr=[0])
    return view

def test_incorporate_adds_to_dataset():
    view = initialize_view()

    row = {0: 1, 1: 1}
    view.incorporate(rowid=1, query=row)
    assert view.X[1] == row  # TEST FAILS

def test_unincorporate_removes_from_dataset():
    view = initialize_view()

    row = {0: 1, 1: 1}
    view.unincorporate(0)
    assert not view.X[0]  # TEST FAILS

```

**Comment by fsaad** [comment]
It is "partially" intended but not ideal. `State.incorporate` updates the dataset, which is a (shared) pointer to the dataset in `View`: https://github.com/probcomp/cgpm/blob/master/src/crosscat/state.py#L231-L233

The current implementation attempts to minimize storing duplicate versions of the same data across multiple composite CGPMs. While not required by the CGPM interface, it is an important optimization in practice.

Related https://github.com/probcomp/cgpm/issues/83 https://github.com/probcomp/cgpm/issues/85

**Comment by leocasarsa** [comment]
1981133 has a proposed solution that is compatible with the current tests.
