### ISSUE TITLE
docker build fails for docker/ubuntu1404-int

### ISSUE THREAD

**Issue by gliptak** [probcomp/cgpm#230]
```
Step 26/28 : RUN ./docker/deps/bayeslite-apsw/pythenv.sh                 ./docker/deps/bayeslite/pythenv.sh                 ./docker/deps/crosscat/pythenv.sh                 ./docker/deps/venture/pythenv.sh                 ./check.sh --integration tests

 ---> Running in 6f082a66d257

/bin/sh: 1: ./docker/deps/bayeslite-apsw/pythenv.sh: not found

The command '/bin/sh -c ./docker/deps/bayeslite-apsw/pythenv.sh                 ./docker/deps/bayeslite/pythenv.sh                 ./docker/deps/crosscat/pythenv.sh                 ./docker/deps/venture/pythenv.sh                 ./check.sh --integration tests' returned a non-zero code: 127
```

**Comment by fsaad** [comment]
Hi @gliptak thank you for the issue request. The docker file `docker/ubuntu1404-int` is not intended to serve as a release artifact. Rather this file is used by our integration server (hosted in house at probcomp-4.csail.mit.edu), and it requires some auxiliary files to exist in the directory:

https://github.com/probcomp/cgpm/blob/91cd8f7f6fce769d7e57f2b33bee2be6cd12ca3b/docker/ubuntu1404-int#L32-L35

I will add a README detailing this information about `docker/ubuntu1404-int`
